name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore backend/backend.sln
      - name: Build
        run: dotnet build backend/backend.sln --no-restore
      - name: Test
        run: dotnet test backend/backend.sln --no-build --verbosity normal
